"""Added payment method model

Revision ID: 3b37bca542d8
Revises: 7661515f5efa
Create Date: 2018-07-14 14:00:13.098573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b37bca542d8'
down_revision = '7661515f5efa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('method', sa.String(length=120), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('method')
    )
    op.drop_table('permissions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('product_permission', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('about_permission', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('blog_permission', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('gallery_permission', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='permissions_pkey'),
    sa.UniqueConstraint('email', name='permissions_email_key')
    )
    op.drop_table('payment_types')
    # ### end Alembic commands ###
