"""revamped company model

Revision ID: 6fb4a903761b
Revises: df3d51cb4bce
Create Date: 2018-07-14 20:13:56.733829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb4a903761b'
down_revision = 'df3d51cb4bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('friday', sa.String(), nullable=True))
    op.add_column('company', sa.Column('group_weekdays', sa.Boolean(), nullable=False))
    op.add_column('company', sa.Column('group_weekends', sa.Boolean(), nullable=False))
    op.add_column('company', sa.Column('hours_title', sa.String(length=50), nullable=True))
    op.add_column('company', sa.Column('monday', sa.String(), nullable=True))
    op.add_column('company', sa.Column('saturday', sa.String(), nullable=True))
    op.add_column('company', sa.Column('show_facebook', sa.Boolean(), nullable=False))
    op.add_column('company', sa.Column('show_instagram', sa.Boolean(), nullable=False))
    op.add_column('company', sa.Column('show_twitter', sa.Boolean(), nullable=False))
    op.add_column('company', sa.Column('special_hours', sa.Boolean(), nullable=False))
    op.add_column('company', sa.Column('sunday', sa.String(), nullable=True))
    op.add_column('company', sa.Column('thursday', sa.String(), nullable=True))
    op.add_column('company', sa.Column('tuesday', sa.String(), nullable=True))
    op.add_column('company', sa.Column('wednesday', sa.String(), nullable=True))
    op.alter_column('company', 'facebook',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('company', 'instagram',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('company', 'sat')
    op.drop_column('company', 'm-f')
    op.drop_column('company', 'sun')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('sun', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('company', sa.Column('m-f', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('company', sa.Column('sat', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('company', 'instagram',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('company', 'facebook',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('company', 'wednesday')
    op.drop_column('company', 'tuesday')
    op.drop_column('company', 'thursday')
    op.drop_column('company', 'sunday')
    op.drop_column('company', 'special_hours')
    op.drop_column('company', 'show_twitter')
    op.drop_column('company', 'show_instagram')
    op.drop_column('company', 'show_facebook')
    op.drop_column('company', 'saturday')
    op.drop_column('company', 'monday')
    op.drop_column('company', 'hours_title')
    op.drop_column('company', 'group_weekends')
    op.drop_column('company', 'group_weekdays')
    op.drop_column('company', 'friday')
    # ### end Alembic commands ###
