"""Added superuser and locked fields to User model

Revision ID: 7661515f5efa
Revises: 
Create Date: 2018-07-12 16:39:51.043165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7661515f5efa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('locked', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('superuser', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'superuser')
    op.drop_column('users', 'locked')
    # ### end Alembic commands ###
