"""added security questions and updated users to match

Revision ID: 9fa6bef6c17d
Revises: fc3d0c66a089
Create Date: 2018-07-24 16:32:29.877008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa6bef6c17d'
down_revision = 'fc3d0c66a089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('images', sa.Column('filename', sa.String(), nullable=True))
    op.add_column('images', sa.Column('url', sa.String(), nullable=True))
    op.drop_column('images', 'img_filename')
    op.drop_column('images', 'img_url')
    op.add_column('users', sa.Column('answer1', sa.Binary(), nullable=False))
    op.add_column('users', sa.Column('answer2', sa.Binary(), nullable=False))
    op.add_column('users', sa.Column('question1', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('question2', sa.Integer(), nullable=False))
    op.drop_column('users', 'superuser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('superuser', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'question2')
    op.drop_column('users', 'question1')
    op.drop_column('users', 'answer2')
    op.drop_column('users', 'answer1')
    op.add_column('images', sa.Column('img_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('img_filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('images', 'url')
    op.drop_column('images', 'filename')
    op.drop_table('questions')
    # ### end Alembic commands ###
