"""Changed name of payment model

Revision ID: df3d51cb4bce
Revises: 3b37bca542d8
Create Date: 2018-07-14 14:05:02.217857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df3d51cb4bce'
down_revision = '3b37bca542d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('method', sa.String(length=120), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('method')
    )
    op.drop_table('payment_types')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('method', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('is_accepted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('icon', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='payment_types_pkey'),
    sa.UniqueConstraint('method', name='payment_types_method_key')
    )
    op.drop_table('payment')
    # ### end Alembic commands ###
